/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_oop_171080200234.ui.components.jinternal_form;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import uas_oop_171080200234.database_service.DatabaseConst;
import uas_oop_171080200234.database_service.DatabaseFactory;
import uas_oop_171080200234.database_service.DatabaseInterface;
import uas_oop_171080200234.database_service.models.JenisFilm;
import uas_oop_171080200234.database_service.repositories.RepositoryInterface;
import uas_oop_171080200234.ui.components.table_model.JenisFilmTableModel;
import uas_oop_171080200234.utils.MessageDialog;

/**
 *
 * @author naufalnibros
 */
public class JenisFilmJInternalForm extends javax.swing.JInternalFrame {
    
    private static RepositoryInterface repository;

    /**
     * Creates new form JenisFilmJInternalForm
     */
    public JenisFilmJInternalForm() {
        super("Data Master Jenis Film", false, true, false, false);
        
        initComponents();
        
        initRepository();
        
        setEdtPencarian();
        
        repository.findAll();
    }
    
    private void initRepository(){
        repository = DatabaseFactory
                .from(DatabaseConst.TABLE_JENIS_FILM)
                .setListener(onDataListener);
    }
    
    private final DatabaseInterface<JenisFilm> onDataListener = new DatabaseInterface<JenisFilm>() {
        
        @Override
        public void onResult(List<JenisFilm> list) {
            setTableData(list);
        }

        @Override
        public void onSuccess() {
            onSuccessSave();
        }

        @Override
        public void onError(String message) {
            JOptionPane.showMessageDialog(null, message, "Terjadi Kesalahan", JOptionPane.PLAIN_MESSAGE);
        }

        @Override
        public void onProcess() {
     
        }
    };
    
    private void onSuccessSave(){
        JOptionPane.showMessageDialog(null, "Data Berhasil diinputkan", "Selamat!", JOptionPane.PLAIN_MESSAGE);
        edtKode.setText(null);
        edtKeterangan.setText(null);
        repository.findAll();
    }
    
    private void setTableData(List<JenisFilm> list){
        JenisFilmTableModel tableModel = new JenisFilmTableModel(list);
        tableData.setModel(tableModel);
    }
    
    private void setEdtPencarian(){
        DocumentListener dl = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent de) {
                repository.search(edtPencarian.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                repository.search(edtPencarian.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
                repository.search(edtPencarian.getText());
            }
        };
        
        edtPencarian.getDocument().addDocumentListener(dl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        edtKeterangan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edtKode = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        edtPencarian = new javax.swing.JTextField();

        jLabel1.setText("KODE :");

        edtKeterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtKeteranganActionPerformed(evt);
            }
        });

        jLabel2.setText("KETERANGAN :");

        edtKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtKodeActionPerformed(evt);
            }
        });

        btnSave.setText("SIMPAN");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Kode", "Keterangan"
            }
        ));
        jScrollPane1.setViewportView(tableData);

        jLabel3.setText("PENCARIAN :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave))
                    .addComponent(edtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edtPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(edtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnReset))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edtPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtKeteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtKeteranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtKeteranganActionPerformed

    private void edtKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtKodeActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        MessageDialog.setMessage("Berhasil Hore!", "Data Berhasil Diinputkan", () -> {
            edtKode.setText(null);
            edtKeterangan.setText(null);
        });
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        repository.create(new JenisFilm(edtKode.getText(), edtKeterangan.getText()));
    }//GEN-LAST:event_btnSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField edtKeterangan;
    private javax.swing.JTextField edtKode;
    private javax.swing.JTextField edtPencarian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableData;
    // End of variables declaration//GEN-END:variables
}
