/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_oop_171080200234.ui.components.jinternal_form;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import uas_oop_171080200234.database_service.DatabaseConst;
import uas_oop_171080200234.database_service.DatabaseFactory;
import uas_oop_171080200234.database_service.DatabaseInterface;
import uas_oop_171080200234.database_service.models.JenisFilm;
import uas_oop_171080200234.database_service.models.VCD;
import uas_oop_171080200234.database_service.repositories.RepositoryInterface;
import uas_oop_171080200234.ui.components.table_model.VCDTableModel;
import uas_oop_171080200234.utils.ComboBoxModelJenisFilm;

/**
 *
 * @author naufalnibros
 */
public class VCDJInternalForm extends javax.swing.JInternalFrame {
    
    private static RepositoryInterface repositoryJenisFilm, repositoryVCD;
    
    private ComboBoxModelJenisFilm boxModelJenisFilm;

    /**
     * Creates new form VCDJInternalForm
     */
    public VCDJInternalForm() {
        super("Data Master VCD", false, true, false, false);
        
        initComponents();
        
        setFormatNumber(txtFieldHargaSewa);
        
        setFormatNumber(txtFieldNilaiDenda);
        
        setEdtPencarian();
        
        setRepositoryModel();
        
        setBoxModelJenisFilm(repositoryJenisFilm.findAll());
        
        repositoryVCD.findAll();
    }
    
    private void setRepositoryModel(){
        repositoryJenisFilm = DatabaseFactory
                .from(DatabaseConst.TABLE_JENIS_FILM)
                .setListener(onDataJenisFilmListener);
        
        repositoryVCD = DatabaseFactory
                .from(DatabaseConst.TABLE_VCD)
                .setListener(onDataVcdListener);
    }
    
    private final DatabaseInterface<JenisFilm> onDataJenisFilmListener = new DatabaseInterface<JenisFilm>() {
        
        @Override
        public void onResult(List<JenisFilm> list) {
        }

        @Override
        public void onSuccess() {
        }

        @Override
        public void onError(String message) {
            JOptionPane.showMessageDialog(getContentPane().getParent().getParent(), message, "Terjadi Kesalahan", JOptionPane.PLAIN_MESSAGE);
        }

        @Override
        public void onProcess() {
            
        }
    };
    
    private final DatabaseInterface<VCD> onDataVcdListener = new DatabaseInterface<VCD>() {
        
        @Override
        public void onResult(List<VCD> list) {
            VCDTableModel tableModel = new VCDTableModel(list);
            tableVcd.setModel(tableModel);
        }

        @Override
        public void onSuccess() {
            onSuccessSave();
        }

        @Override
        public void onError(String message) {
            JOptionPane.showMessageDialog(getContentPane().getParent().getParent(), message, "Terjadi Kesalahan", JOptionPane.PLAIN_MESSAGE);
        }

        @Override
        public void onProcess() {
     
        }
    };
    
    private void setBoxModelJenisFilm(List<JenisFilm> listJenisModel){
        try {
            JenisFilm[] jenisFilms = new JenisFilm[listJenisModel.size() + 1];
        
            for (int i = 0; i < listJenisModel.size(); i++) {
                jenisFilms[i] = listJenisModel.get(i);
            }
            
            boxModelJenisFilm = new ComboBoxModelJenisFilm(jenisFilms);
            comboBoxJenisFilm.setModel(boxModelJenisFilm);
                    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Terjadi Kesalahan", JOptionPane.PLAIN_MESSAGE);
            dispose();
        }
    }
    
    private void onSuccessSave(){
        JOptionPane.showMessageDialog(getContentPane().getParent().getParent(), "Data Berhasil diinputkan", "Selamat!", JOptionPane.PLAIN_MESSAGE);
        setResetField();
        repositoryVCD.findAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFieldNama = new javax.swing.JTextField();
        txtFieldKode = new javax.swing.JTextField();
        comboBoxJenisFilm = new javax.swing.JComboBox<>();
        txtFieldHargaSewa = new javax.swing.JTextField();
        txtFieldNilaiDenda = new javax.swing.JTextField();
        edtPencarian = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableVcd = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel1.setText("KODE :");

        jLabel2.setText("NAMA :");

        jLabel3.setText("JENIS FILM :");

        jLabel4.setText("HARGA SEWA :");

        jLabel5.setText("NILAI DENDA :");

        jLabel6.setText("PENCARIAN :");

        tableVcd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tableVcd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO.", "KODE", "NAMA", "JENIS FILM", "HARGA SEWA", "NILAI DENDA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableVcd);

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldNama)
                    .addComponent(comboBoxJenisFilm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(txtFieldKode, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtFieldHargaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtFieldNilaiDenda, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtPencarian))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(txtFieldKode, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxJenisFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addComponent(txtFieldHargaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addComponent(txtFieldNilaiDenda, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnReset))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(edtPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        setResetField();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        onActionSave();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void setResetField(){
        txtFieldHargaSewa.setText(null);
        txtFieldKode.setText(null);
        txtFieldKode.setText(null);
        txtFieldNama.setText(null);
        txtFieldNilaiDenda.setText(null);
    }
    
    private void onActionSave(){
        try {
            repositoryVCD.create(
                new VCD(
                        txtFieldKode.getText(), 
                        txtFieldNama.getText(), 
                        Integer.valueOf(txtFieldNilaiDenda.getText()),
                        Integer.valueOf(txtFieldHargaSewa.getText()), 
                        boxModelJenisFilm.getSelectedItem())
            );
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Terjadi Kesalahan", JOptionPane.PLAIN_MESSAGE);
        }
    }
    
    private void setEdtPencarian(){
        DocumentListener dl = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent de) {
                repositoryVCD.search(edtPencarian.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                repositoryVCD.search(edtPencarian.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
                repositoryVCD.search(edtPencarian.getText());
            }
        };
        
        edtPencarian.getDocument().addDocumentListener(dl);
    }
    
    private void setFormatNumber(JTextField field){
        field.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent ke) {
                if (ke.getKeyChar() >= '0' && ke.getKeyChar() <= '9') {
                   field.setEditable(true);
                } else {
                   JOptionPane.showMessageDialog(null, "Masukkan hanya bilangan numerik(1 - 9)", "Peringatan!", JOptionPane.PLAIN_MESSAGE);
                   field.setText(null);
                }
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<JenisFilm> comboBoxJenisFilm;
    private javax.swing.JTextField edtPencarian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tableVcd;
    private javax.swing.JTextField txtFieldHargaSewa;
    private javax.swing.JTextField txtFieldKode;
    private javax.swing.JTextField txtFieldNama;
    private javax.swing.JTextField txtFieldNilaiDenda;
    // End of variables declaration//GEN-END:variables
}
