/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_oop_171080200234.ui.panel;

import java.awt.Dimension;
import javax.swing.JInternalFrame;
import uas_oop_171080200234.database_service.repositories.JenisFilmRepository;
import uas_oop_171080200234.ui.components.jinternal_form.JenisFilmJInternalForm;
import uas_oop_171080200234.ui.components.jinternal_form.VCDJInternalForm;
import uas_oop_171080200234.utils.JasperUtils;

/**
 *
 * @author naufalnibros
 */
public class MainPanel extends javax.swing.JFrame {

    /**
     * Creates new form ExamplePanel
     */
    public MainPanel() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }
    
    private void openForm(JInternalFrame form){
        Dimension desktopSize = dekstopPane.getSize();
        Dimension jInternalFrameSize = form.getSize();
        form.setLocation((desktopSize.width - jInternalFrameSize.width)/2, (desktopSize.height- jInternalFrameSize.height)/2);
        dekstopPane.add(form);        
        form.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        dekstopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        onMenuMasterJenis = new javax.swing.JMenuItem();
        onMenuMasterVcd = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        onMenuReportJenis = new javax.swing.JMenuItem();
        onMenuReportVcd = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dekstopPaneLayout = new javax.swing.GroupLayout(dekstopPane);
        dekstopPane.setLayout(dekstopPaneLayout);
        dekstopPaneLayout.setHorizontalGroup(
            dekstopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dekstopPaneLayout.setVerticalGroup(
            dekstopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("Data Master");

        onMenuMasterJenis.setMnemonic('o');
        onMenuMasterJenis.setText("Jenis Film");
        onMenuMasterJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onMenuMasterJenisActionPerformed(evt);
            }
        });
        fileMenu.add(onMenuMasterJenis);

        onMenuMasterVcd.setMnemonic('s');
        onMenuMasterVcd.setText("VCD");
        onMenuMasterVcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onMenuMasterVcdActionPerformed(evt);
            }
        });
        fileMenu.add(onMenuMasterVcd);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Laporan");

        onMenuReportJenis.setMnemonic('t');
        onMenuReportJenis.setText("iReport Jenis Film");
        onMenuReportJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onMenuReportJenisActionPerformed(evt);
            }
        });
        editMenu.add(onMenuReportJenis);

        onMenuReportVcd.setMnemonic('y');
        onMenuReportVcd.setText("iReport VCD");
        editMenu.add(onMenuReportVcd);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dekstopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dekstopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onMenuMasterJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onMenuMasterJenisActionPerformed
        openForm(new JenisFilmJInternalForm());
    }//GEN-LAST:event_onMenuMasterJenisActionPerformed

    private void onMenuMasterVcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onMenuMasterVcdActionPerformed
        openForm(new VCDJInternalForm());
    }//GEN-LAST:event_onMenuMasterVcdActionPerformed

    private void onMenuReportJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onMenuReportJenisActionPerformed
        JasperUtils
                .set("Report Master Jenis Film", this)
                .open(new JenisFilmRepository().getReport(), "Report/FileReport.jasper");
    }//GEN-LAST:event_onMenuReportJenisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dekstopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem onMenuMasterJenis;
    private javax.swing.JMenuItem onMenuMasterVcd;
    private javax.swing.JMenuItem onMenuReportJenis;
    private javax.swing.JMenuItem onMenuReportVcd;
    // End of variables declaration//GEN-END:variables

}
