/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_oop_171080200234.ui.components.dialog_form;

import java.util.List;
import javax.swing.JOptionPane;
import uas_oop_171080200234.database_service.DatabaseConst;
import uas_oop_171080200234.database_service.DatabaseFactory;
import uas_oop_171080200234.database_service.DatabaseInterface;
import uas_oop_171080200234.database_service.models.JenisFilm;
import uas_oop_171080200234.database_service.repositories.RepositoryInterface;
import uas_oop_171080200234.ui.OnCallBackComponent;

/**
 *
 * @author naufalnibros
 */
public class JenisFilmDialogForm extends javax.swing.JDialog {
    
    private static RepositoryInterface repository;
    
    private OnCallBackComponent callBackComponent;

    public void setCallBack(OnCallBackComponent callBackComponent){
        this.callBackComponent = callBackComponent;
    }

    /**
     * Creates new form DialogJenisFilm
     */
    public JenisFilmDialogForm() {
        initComponents();
        
        setTitle("Entry Jenis Film");
        
        repository = DatabaseFactory
                .from(DatabaseConst.TABLE_JENIS_FILM)
                .setListener(onDatabaseListener);
        
        edtKode.setText("");
        edtKeterangan.setText("");
    }
    
    /**
     * Set OnCallBackComponent Listener
     * @param callBackComponent
     */
    
    private final DatabaseInterface<JenisFilm> onDatabaseListener = new DatabaseInterface<JenisFilm>() {
        
        @Override
        public void onResult(List<JenisFilm> list) {
            
        }

        @Override
        public void onSuccess() {
            JOptionPane.showMessageDialog(null, "Data Berhasil diinputkan", "Selamat!", JOptionPane.PLAIN_MESSAGE);
            callBackComponent.restart();
            JenisFilmDialogForm.this.setVisible(false);
        }

        @Override
        public void onError(String message) {
            JOptionPane.showMessageDialog(null, message, "Terjadi Kesalahan", JOptionPane.PLAIN_MESSAGE);
        }

        @Override
        public void onProcess() {
     
        }
    };
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        edtKode = new javax.swing.JTextField();
        edtKeterangan = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnBatalkan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Kode :");

        jLabel3.setText("Keterangan :");

        edtKode.setText("jTextField1");
        edtKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtKodeActionPerformed(evt);
            }
        });

        edtKeterangan.setText("jTextField1");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatalkan.setText("Batalkan");
        btnBatalkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalkanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtKeterangan)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBatalkan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                        .addComponent(btnSimpan))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(edtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatalkan)
                    .addComponent(btnSimpan))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        repository.create(new JenisFilm(edtKode.getText(), edtKeterangan.getText()));
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalkanActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnBatalkanActionPerformed

    private void edtKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtKodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JenisFilmDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JenisFilmDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JenisFilmDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JenisFilmDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JenisFilmDialogForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalkan;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JTextField edtKeterangan;
    private javax.swing.JTextField edtKode;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
