/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_oop_171080200234.ui.components.dialog_form;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import uas_oop_171080200234.database_service.DatabaseConst;
import uas_oop_171080200234.database_service.DatabaseFactory;
import uas_oop_171080200234.database_service.DatabaseInterface;
import uas_oop_171080200234.database_service.models.JenisFilm;
import uas_oop_171080200234.database_service.models.VCD;
import uas_oop_171080200234.database_service.repositories.RepositoryInterface;
import uas_oop_171080200234.ui.OnCallBackComponent;
import uas_oop_171080200234.utils.ComboBoxModelJenisFilm;

/**
 *
 * @author naufalnibros
 */
public class VCDDialogForm extends javax.swing.JFrame {
    
    private static RepositoryInterface repositoryJenisFilm, repositoryVCD;
    
    private OnCallBackComponent callBackComponent;
    
    private ComboBoxModelJenisFilm boxModelJenisFilm;
    
    public void setCallBack(OnCallBackComponent callBackComponent){
        this.callBackComponent = callBackComponent;
    }

    /**
     * Creates new form DialogFormVCD
     */
    public VCDDialogForm() {
        initComponents();
        
        setTitle("Entry VCD");
        
        setRepositoryModel();
        
        setBoxModelJenisFilm(
                repositoryJenisFilm.findAll()
        );
        
        setFieldNumber();
    }
    
    private void setFieldNumber(){
        setFormatNumber(txtFieldNilaiDenda);
        setFormatNumber(txtFieldHargaSewa);
    }
    
    private void setFormatNumber(JTextField field){
        field.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent ke) {
                if (ke.getKeyChar() >= '0' && ke.getKeyChar() <= '9') {
                   field.setEditable(true);
                } else {
                   JOptionPane.showMessageDialog(null, "Masukkan hanya bilangan numerik(1 - 9)", "Peringatan!", JOptionPane.PLAIN_MESSAGE);
                   field.setText(null);
                }
            }
            
        });
    }
    
    private void setRepositoryModel(){
        repositoryJenisFilm = DatabaseFactory
                .from(DatabaseConst.TABLE_JENIS_FILM)
                .setListener(databaseInterfaceJenisFilm);
        
        repositoryVCD = DatabaseFactory
                .from(DatabaseConst.TABLE_VCD)
                .setListener(databaseInterfaceVCD);
    }
    
    private void setBoxModelJenisFilm(List<JenisFilm> listJenisModel){
        try {
            JenisFilm[] jenisFilms = new JenisFilm[listJenisModel.size() + 1];
        
            for (int i = 0; i < listJenisModel.size(); i++) {
                jenisFilms[i] = listJenisModel.get(i);
            }
            
            boxModelJenisFilm = new ComboBoxModelJenisFilm(jenisFilms);
            comboBoxJenisFilm.setModel(boxModelJenisFilm);
                    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Terjadi Kesalahan", JOptionPane.PLAIN_MESSAGE);
            VCDDialogForm.this.setVisible(false);
        }
    }
    
    private final DatabaseInterface<JenisFilm> databaseInterfaceJenisFilm = new DatabaseInterface<JenisFilm>() {
        
        @Override
        public void onResult(List<JenisFilm> list) {
        }

        @Override
        public void onSuccess() {
        }

        @Override
        public void onError(String message) {
            JOptionPane.showMessageDialog(null, message, "Terjadi Kesalahan", JOptionPane.PLAIN_MESSAGE);
        }

        @Override
        public void onProcess() {
     
        }
    };
    
    private final DatabaseInterface<VCD> databaseInterfaceVCD = new DatabaseInterface<VCD>() {
        
        @Override
        public void onResult(List<VCD> list) {
        }

        @Override
        public void onSuccess() {
            JOptionPane.showMessageDialog(null, "Data Berhasil diinputkan", "Selamat!", JOptionPane.PLAIN_MESSAGE);
            callBackComponent.restart();
            VCDDialogForm.this.setVisible(false);
        }

        @Override
        public void onError(String message) {
            JOptionPane.showMessageDialog(null, message, "Terjadi Kesalahan", JOptionPane.PLAIN_MESSAGE);
        }

        @Override
        public void onProcess() {
     
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFieldKode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFieldNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboBoxJenisFilm = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtFieldHargaSewa = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFieldNilaiDenda = new javax.swing.JTextField();
        btnBatalkan = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kode :");

        txtFieldKode.setToolTipText("Kode VCD (Pastikan Harus Berbeda)");

        jLabel2.setText("Nama :");

        txtFieldNama.setToolTipText("Nama VCD");
        txtFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldNamaActionPerformed(evt);
            }
        });

        jLabel3.setText("Jenis Film :");

        comboBoxJenisFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxJenisFilmActionPerformed(evt);
            }
        });

        jLabel4.setText("Harga Sewa :");

        txtFieldHargaSewa.setToolTipText("Harga Sewa");
        txtFieldHargaSewa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldHargaSewaKeyTyped(evt);
            }
        });

        jLabel5.setText("NIlai Denda :");

        txtFieldNilaiDenda.setToolTipText("Nilai Denda");

        btnBatalkan.setText("Batalkan");
        btnBatalkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalkanActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBatalkan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                        .addComponent(btnSimpan))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(txtFieldKode, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(txtFieldNama)
                                .addComponent(jLabel3)
                                .addComponent(comboBoxJenisFilm, 0, 341, Short.MAX_VALUE))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtFieldNilaiDenda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                .addComponent(txtFieldHargaSewa, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldKode, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxJenisFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldHargaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldNilaiDenda, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatalkan)
                    .addComponent(btnSimpan))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalkanActionPerformed
        setVisible(false);        
    }//GEN-LAST:event_btnBatalkanActionPerformed

    private void comboBoxJenisFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxJenisFilmActionPerformed
        
    }//GEN-LAST:event_comboBoxJenisFilmActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        repositoryVCD.create(
                new VCD(
                        txtFieldKode.getText(), 
                        txtFieldNama.getText(), 
                        Integer.valueOf(txtFieldNilaiDenda.getText()),
                        Integer.valueOf(txtFieldHargaSewa.getText()), 
                        boxModelJenisFilm.getSelectedItem())
        );
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldNamaActionPerformed

    private void txtFieldHargaSewaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldHargaSewaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldHargaSewaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCDDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCDDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCDDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCDDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCDDialogForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalkan;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<JenisFilm> comboBoxJenisFilm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtFieldHargaSewa;
    private javax.swing.JTextField txtFieldKode;
    private javax.swing.JTextField txtFieldNama;
    private javax.swing.JTextField txtFieldNilaiDenda;
    // End of variables declaration//GEN-END:variables
}
